conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import auth
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('contact_submit/', views.contact_submit, name='contact_submit'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nazwa użytkownika',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Hasło',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nazwa użytkownika',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Hasło',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Powtórz Hasło',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from item.models import Category, Item

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-id')[:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def contact(request):
    return render(request, 'core/contact.html')


def contact_submit(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        # Compose the email message
        subject = 'Contact Form Submission'
        message_body = f'Name: {name}\nEmail: {email}\n\nMessage:\n{message}'

        # Send the email
        send_mail(subject, message_body, settings.EMAIL_HOST_USER,
                  ['nszmygalow@gmail.com'])

        # Redirect to a success page (optional)
        return HttpResponseRedirect(reverse('core:contact_success'))

    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/base.html
<!doctype html>
<html lang="pl">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | SellEasy </title>
    
    <!-- Include Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <script>
        function toggleMenu() {
            const menu = document.getElementById('mobile-menu');
            menu.classList.toggle('hidden');
        }
    </script>
</head>
<body class="bg-blue-50 text-blue-900 font-sans">
    <!-- Navigation Bar -->
    <nav class="py-6 px-6 flex justify-between items-center border-b border-blue-300 bg-blue-200">
        <a href="/" class="text-2xl font-semibold">
            <img src="{% static 'shopping-basket.png' %}" alt="SellEasy Logo" class="inline-block h-12 mr-2"> SellEasy 
        </a>

        <div class="hidden md:flex space-x-6 items-center">
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-blue-700">Dodaj przedmiot</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-blue-700">Przeglądaj</a>

            {% if request.user.is_authenticated %}
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Skrzynka odbiorcza</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Moje przedmioty</a>
                <form class="inline"  action="{% url 'core:logout' %}" method="post"> 
                    {% csrf_token %} 
                    <button type="submit" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Wyjdz</button>    
                </form>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Zarejestruj się</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-600 text-white rounded-xl hover:bg-gray-700">Zaloguj się</a>
            {% endif %}
        </div>

        <!-- Hamburger Icon -->
        <button class="block md:hidden text-blue-600 focus:outline-none" onclick="toggleMenu()">
            <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
            </svg>
        </button>
    </nav>

    <!-- Mobile Menu -->
    <div id="mobile-menu" class="hidden md:hidden px-6 py-6 bg-blue-200 border-t border-blue-300">
        <a href="{% url 'item:new' %}" class="block text-lg font-semibold hover:text-blue-700 py-2">Dodaj przedmiot</a>
        <a href="{% url 'item:items' %}" class="block text-lg font-semibold hover:text-blue-700 py-2">Przeglądaj</a>

        {% if request.user.is_authenticated %}
            <a href="{% url 'conversation:inbox' %}" class="block px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700 my-2">Skrzynka odbiorcza</a>
            <a href="{% url 'dashboard:index' %}" class="block px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700 my-2">Moje przedmioty</a>
            <form class="block" action="{% url 'core:logout' %}" method="post"> 
                {% csrf_token %} 
                <button type="submit" class="block w-full px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700 my-2">Wyjdz</button>    
            </form>
        {% else %}
            <a href="{% url 'core:signup' %}" class="block px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700 my-2">Zarejestruj się</a>
            <a href="{% url 'core:login' %}" class="block px-6 py-3 text-lg font-semibold bg-gray-600 text-white rounded-xl hover:bg-gray-700 my-2">Zaloguj się</a>
        {% endif %}
    </div>

    <!-- Main Content -->
    <div class="px-6 py-8">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="py-6 px-6 flex flex-col md:flex-row justify-between bg-blue-800 text-white">
        <div class="w-full md:w-2/3 pr-10 mb-6 md:mb-0">
            <h3 class="mb-4 text-xl font-semibold">O nas</h3>
            <p class="text-lg">SellEasy to intuicyjna i przyjazna dla użytkownika platforma zaprojektowana w celu ułatwienia użytkownikom sprzedaży ich rzeczy. Tutaj każdy może szybko i bezpiecznie wystawić na sprzedaż dowolne towary, od ubrań i elektroniki po meble i przedmioty kolekcjonerskie. Platforma koncentruje się na łatwości użytkowania i przejrzystości transakcji.</p>
        </div>
        <div class="w-full md:w-1/3">
            <h3 class="mb-4 text-xl font-semibold">Menu</h3>
            <ul class="space-y-2">
                <li><a href="{% url 'core:contact' %}" class="text-lg hover:text-blue-200">Kontakt</a></li>
                <li><a href="{% static 'polityka_prywatnosci.pdf' %}" download class="text-lg hover:text-blue-200">Polityka prywatności</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Kontakt{% endblock %}

{% block content %}
    <div class="px-6 py-8 bg-blue-50 rounded-xl">
        <h1 class="text-3xl font-semibold text-blue-800 mb-6">Strona kontaktowa</h1>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
                <h2 class="text-xl font-semibold text-blue-800 mb-4">Informacje kontaktowe</h2>
                <p class="text-lg text-blue-700"><strong>Adres:</strong> ul. Przykładowa 123, 00-000 Warszawa</p>
                <p class="text-lg text-blue-700"><strong>Telefon:</strong> +48 123 456 789</p>
                <p class="text-lg text-blue-700"><strong>Email:</strong> kontakt@bajoro.pl</p>
            </div>

            <div>
                <h2 class="text-xl font-semibold text-blue-800 mb-4">Formularz kontaktowy</h2>
      <form action="#" method="POST">
                    {% csrf_token %}
                    <div class="mb-4">
                        <label for="name" class="block text-lg text-blue-700">Imię i nazwisko:</label>
                        <input type="text" id="name" name="name" class="w-full px-4 py-2 rounded-lg border border-blue-300 focus:outline-none focus:border-blue-500" required>
                    </div>
                    <div class="mb-4">
                        <label for="email" class="block text-lg text-blue-700">Email:</label>
                        <input type="email" id="email" name="email" class="w-full px-4 py-2 rounded-lg border border-blue-300 focus:outline-none focus:border-blue-500" required>
                    </div>
                    <div class="mb-4">
                        <label for="message" class="block text-lg text-blue-700">Wiadomość:</label>
                        <textarea id="message" name="message" rows="4" class="w-full px-4 py-2 rounded-lg border border-blue-300 focus:outline-none focus:border-blue-500" required></textarea>
                    </div>
                    <button type="submit" class="px-6 py-3 text-lg font-semibold bg-blue-600 text-white rounded-xl hover:bg-blue-700">Wyślij</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Witaj{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-blue-50 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Najnowsze przedmioty</h2>

        <div class="grid grid-cols-6 gap-3">
            {% for item in items %}
                <div class="shadow-lg rounded-xl overflow-hidden" >
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="w-full h-80">
                            <img src="{{ item.image.url }}" class="object-cover w-full h-full">
                        </div>
			<div>	
<div class="flex flex-col justify-between bg-white p-6 rounded-lg shadow-lg">
    <h2 class="text-2xl font-semibold truncate text-gray-900">{{ item.name }}</h2>
    <p class="text-blue-700 mt-4 text-xl font-medium">{{ item.price }} zł</p>
</div>
                        </div>

                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

  {% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Zaloguj się{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-blue-50 rounded-xl">
    <h1 class="mb-6 text-3xl text-blue-800">Zaloguj się</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2 text-blue-800">Nazwa użytkownika</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2 text-blue-800">Hasło</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-600 hover:bg-blue-700 rounded-xl text-white">Zaloguj</button>
    </form>
</div>
{% endblock %}

core/templates/core/polityka.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Polityka prywatności{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-blue-50 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Polityka Prywatności</h2>

        <div class="prose">
            <h3 class="text-xl mb-4">1. Wprowadzenie</h3>
            <p>Twoja prywatność jest dla nas bardzo ważna. Niniejsza polityka prywatności wyjaśnia, jakie informacje zbieramy, jak je wykorzystujemy i jakie masz prawa w związku z Twoimi danymi osobowymi.</p>

            <h3 class="text-xl mb-4">2. Jakie dane zbieramy</h3>
            <p>Możemy zbierać następujące informacje:</p>
            <ul class="list-disc list-inside">
                <li>Imię i nazwisko</li>
                <li>Adres e-mail</li>
                <li>Numer telefonu</li>
                <li>Adres IP</li>
                <li>Informacje o przeglądarce i urządzeniu</li>
            </ul>

            <h3 class="text-xl mb-4">3. Jak wykorzystujemy Twoje dane</h3>
            <p>Twoje dane mogą być wykorzystywane do:</p>
            <ul class="list-disc list-inside">
                <li>Świadczenia naszych usług</li>
                <li>Komunikacji z Tobą</li>
                <li>Polepszania naszych usług</li>
                <li>Analizy statystycznej</li>
            </ul>

            <h3 class="text-xl mb-4">4. Udostępnianie danych</h3>
            <p>Nie udostępniamy Twoich danych osobom trzecim bez Twojej zgody, z wyjątkiem przypadków wymaganych prawem.</p>

            <h3 class="text-xl mb-4">5. Twoje prawa</h3>
            <p>Masz prawo do:</p>
            <ul class="list-disc list-inside">
                <li>Dostępu do swoich danych</li>
                <li>Poprawiania swoich danych</li>
                <li>Usuwania swoich danych</li>
                <li>Ograniczenia przetwarzania danych</li>
                <li>Sprzeciwu wobec przetwarzania danych</li>
            </ul>

            <h3 class="text-xl mb-4">6. Zmiany w polityce prywatności</h3>
            <p>Możemy aktualizować niniejszą politykę prywatności od czasu do czasu, publikując nowe wersje na naszej stronie internetowej. Prosimy o regularne sprawdzanie tej strony, aby być na bieżąco z wszelkimi zmianami.</p>

            <h3 class="text-xl mb-4">7. Kontakt</h3>
            <p>Jeśli masz jakiekolwiek pytania dotyczące tej polityki prywatności lub sposobu, w jaki przetwarzamy Twoje dane, prosimy o kontakt pod adresem e-mail: <a href="mailto:kontakt@przyklad.pl" class="text-blue-700">kontakt@przyklad.pl</a>.</p>
        </div>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Zarejestruj się{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-blue-50 rounded-xl">
    <h1 class="mb-6 text-3xl text-blue-800">Zarejestruj się</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label for="username" class="inline-block mb-2 text-blue-800">Nazwa użytkownika</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label for="email" class="inline-block mb-2 text-blue-800">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label for="password1" class="inline-block mb-2 text-blue-800">Hasło</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label for="password2" class="inline-block mb-2 text-blue-800">Powtórz hasło</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-blue-600 hover:bg-blue-700 rounded-xl text-white">Zarejestruj</button>
    </form>
</div>
{% endblock %}