conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import auth
from django.urls import path
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('contact_submit/', views.contact_submit, name='contact_submit'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',
         authentication_form=LoginForm), name='login'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}),
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

item/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='nazwa')

    class Meta:
        ordering = ('name',)
        verbose_name = 'kategoria'
        verbose_name_plural = 'kategorie'

    def __str__(self):
        return self.name


class Item(models.Model):
    category = models.ForeignKey(
        Category, related_name='items', on_delete=models.CASCADE, verbose_name='kategoria')
    name = models.CharField(max_length=255, verbose_name='nazwa')
    description = models.TextField(blank=True, null=True, verbose_name='opis')
    price = models.FloatField(verbose_name='cena')
    image = models.ImageField(upload_to='item_images',
                              null=True, verbose_name='obraz')
    is_sold = models.BooleanField(default=False, verbose_name='sprzedane')
    created_by = models.ForeignKey(
        User, related_name='items', on_delete=models.CASCADE, verbose_name='utworzone przez')
    created_at = models.DateTimeField(
        auto_now_add=True, verbose_name='utworzono')

    class Meta:
        verbose_name = 'przedmiot'
        verbose_name_plural = 'przedmioty'

    def __str__(self):
        return self.name

item/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _  # Import for translation

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Wybierz kategorię...')
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Nazwa...')
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Opis...')
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Cena...')
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Wybierz zdjęcie...')
            })
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].label = _('Kategoria')
        self.fields['name'].label = _('Nazwa')
        self.fields['description'].label = _('Opis')
        self.fields['price'].label = _('Cena')
        self.fields['image'].label = _('Zdjęcie')


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Nazwa...')
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Opis...')
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Cena...')
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES,
                'placeholder': _('Wybierz zdjęcie...')
            })
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].label = _('Nazwa')
        self.fields['description'].label = _('Opis')
        self.fields['price'].label = _('Cena')
        self.fields['image'].label = _('Zdjęcie')
        self.fields['is_sold'].label = _('Czy sprzedane?')

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewItemForm, EditItemForm
from .models import Category, Item
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if category_id:
        items = items.filter(category_id=category_id)

    if query:
        items = items.filter(Q(name__icontains=query) |
                             Q(description__icontains=query))
    paginator = Paginator(items, 10)  # 9 items per page
    page_number = request.GET.get('page')
    try:
        items = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        items = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        items = paginator.page(paginator.num_pages)
    return render(request, 'item/items.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id)
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(
        category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Nowy przedmiot',
    })


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-4 gap-6">
    <div class="col-span-1 mx-auto">
        <div class="w-full h-96">
            <img src="{{ item.image.url }}" class="object-cover w-full h-full rounded-xl">
        </div>
    </div>

    <div class="col-span-3 p-6 bg-blue-200 rounded-xl text-blue-800">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-700"><strong>Cena: </strong>{{ item.price }} zł</p>
        <p class="text-gray-700"><strong>Sprzedawca: </strong>{{ item.created_by.username }}</p>
    
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Opis:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}

        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl text-blue-800">
                <p>To jest twój przedmiot!</p>

                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Edytuj</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Usuń</a>
            </div>
        {% else %}  
            <a href="{% url 'conversation:new' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Skontaktuj się ze sprzedawcą</a>
        {% endif %}
    </div>
</div>

<div class="mt-12 px-6 py-12 bg-blue-200 rounded-xl text-blue-800">
    <h2 class="mb-12 text-2xl text-center">Podobne przedmioty</h2>

    <div class="grid grid-cols-6 gap-6">
        {% for item in related_items %}
            <div class="shadow-lg rounded-xl overflow-hidden">
                <a href="{% url 'item:detail' item.id %}">
                    <div class="w-full h-56">
                        <img src="{{ item.image.url }}" class="object-cover w-full h-full">
                    </div>

                    <div class="p-6 bg-gray-100">
                        <h2 class="text-2xl font-semibold truncate">{{ item.name }}</h2>
                        <p class="text-blue-700 mt-2">{{ item.price }} zł</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-blue-50 rounded-xl">
    <h1 class="mb-6 text-3xl text-blue-800">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {% for field in form %}
                <div class="mb-3">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.help_text %}
                        <small class="text-gray-500">{{ field.help_text }}</small>
                    {% endif %}
                    {% if field.errors %}
                        <p class="text-red-500">{{ field.errors }}</p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-blue-600 hover:bg-blue-700 rounded-xl text-white">Wyślij</button>
    </form>
</div>
{% endblock %}

item/templates/item/items.html
{% extends 'core/base.html' %}

{% block title %}Przedmioty{% endblock %}
{% load static %}
{% block content %}
<div class="pb-6 grid grid-cols-7 gap-4 bg-blue-50">
    <div class="col-span-2">
        <form method="get" action="{% url 'item:items' %}">
            <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Znajdź rower, krzesło lub samochód...">
            <button class="mt-2 py-4 px-8 text-lg bg-blue-600 text-white rounded-xl hover:bg-blue-700">Szukaj</button>
        </form>
        <hr class="my-6">
        <p class="font-semibold text-blue-800">Kategorie</p>
        <ul>
            {% for category in categories %}
                <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-blue-200{% endif %}" data-url="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}">
                    <span class="text-blue-800 cursor-pointer">{{ category.name }}</span>
                </li>
            {% endfor %}
        </ul>
        <hr class="my-6">
        <p class="font-semibold text-blue-800">Wyczyść filtry</p>
        <ul>
            <li data-url="{% url 'item:items' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white cursor-pointer">Wyczyść</li>
        </ul>
    </div>

    <div class="col-span-5">
        <div class="grid grid-cols-5 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <div class="relative">
                            <img src="{{ item.image.url }}" class="w-full h-56 object-cover object-center" alt="{{ item.name }}">
                            <span class="absolute top-0 right-0 bg-blue-500 text-white py-1 px-3 rounded-tr-lg rounded-bl-lg text-xs font-semibold">{{ item.category }}</span>
                        </div>
                        <div class="p-6 bg-gray-50 rounded-b-xl">
                            <h2 class="text-2xl text-blue-800 font-semibold truncate">{{ item.name }}</h2>
                            <p class="text-blue-700 mt-2">{{ item.price }} zł</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
        {% if items.has_other_pages %}
            <div class="mt-6 flex justify-center">
                <ul class="flex space-x-2">
                    {% if items.has_previous %}
                        <li><a href="?page=1"><img src="{% static 'left.png' %}" alt="Previous" style="width: 30px; height: 20px;"></a></li>
                        <li><a href="?page={{ items.previous_page_number }}"><img src="{% static 'left-arrow.png' %}" alt="Previous" style="width: 20px; height: 20px;"></a></li>
                    {% endif %}
                    {% for num in items.paginator.page_range %}
                        {% if num == items.number %}
                            <li><span class="py-2 px-4 bg-blue-600 text-white rounded-lg">{{ num }}</span></li>
                        {% else %}
                            <li><a href="?page={{ num }}" class="py-2 px-4 bg-blue-200 text-blue-800 rounded-lg hover:bg-blue-300 focus:outline-none focus:bg-blue-300">{{ num }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if items.has_next %}
                        <li><a href="?page={{ items.next_page_number }}"><img src="{% static 'right-arrow.png' %}" alt="Next" style="width: 30px; height: 20px;"></a></li>
                        <li><a href="?page={{ items.paginator.num_pages }}"><img src="{% static 'right.png' %}" alt="Next" style="width: 20px; height: 20px;"></a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('li[data-url]').forEach(function(li) {
            li.addEventListener('click', function() {
                window.location.href = li.getAttribute('data-url');
            });
        });
    });
</script>
{% endblock %}